# This is a basic workflow to help you get started with Actions

# Name that will appear in the UI
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

# trigger for the workflow
on: [push]


jobs:
  # name of job
  check-bats-version:
    # configures the runner
    runs-on: ubuntu-latest
    steps:
      # executes an action
      - uses: actions/checkout@v3
      # executes an action with a name
      - name: Set up node action
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  
  # we have another job
  another-job:
    runs-on: ubuntu-latest
    # that depends on another job
    needs: check-bats-version
    # environment variables
    env:
      Greeting: Hello
    steps:
      - run: echo $Greeting

  # a job that runs over a matrix of inputs
  matrix-job:
    strategy:
      fail-fast: true
      matrix:
        number-one: [1,2,3]
    runs-on: ubuntu-latest
    needs: another-job
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ matrix.number-one }}"
      - name: Run check even
        run: ./check-even.bash ${{ matrix.number-one }}
        shell: bash

  # a job that grabs some artifacts : shared between jobs
  save-output-job:
    name: Save output
    runs-on: ubuntu-latest
    outputs:
      output1: $${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with: 
          name: output-log-file
          path: output.log

  download-output:
    needs: save-output-job
    runs-on: ubuntu-latest
    name: Download output

    steps:
      - uses: actions/download-artifact@v3
        with: 
          name: output-log-file
      - run: cat output.log
      - run: echo ${{ needs.save-output-job.outputs.output1}}